// features/export-project/constants/project-template-files.ts



import { GeneratedFile } from "@/core/types/generated-file.types";
import { slugifyPathSegment } from "@/features/code-generator/utils/path-utils";

const PACKAGE_JSON = (projectSlug: string) => `{
  "name": "${projectSlug}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.2.9",
    "react": "19.2.4",
    "react-dom": "19.2.4",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "lucide-react": "^1.21.0",
    "radix-ui": "^1.6.0",
    "tailwind-merge": "^3.6.0"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4",
    "typescript": "^5"
  }
}
`;

const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const NEXT_CONFIG_TS = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;

const POSTCSS_CONFIG_MJS = `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`;

const GLOBALS_CSS = `@import "tailwindcss";

html, body {
  height: 100%;
  margin: 0;
}
`;

const LAYOUT_TSX = (projectName: string) => `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Generated by 26VisualBuilder",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

// Nội dung y hệt file shadcn CLI cài — luôn nhúng cố định, không phụ thuộc project có
// dùng shadcn.* node nào hay không, vì rẻ (vài trăm byte) và mọi file ui/*.tsx (Phase 2)
// đều import file này. Thiếu nó là lỗi Module not found ngay khi build.
const LIB_UTILS_TS = `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;

const GITIGNORE = `node_modules
.next
.env*.local
.DS_Store
*.tsbuildinfo
`;

const README_MD = (projectName: string) => `# ${projectName}

Generated by **26VisualBuilder**.

## Stack
- Next.js 16
- React 19
- Tailwind CSS v4
- shadcn/ui

## Run

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

Mở [http://localhost:3000](http://localhost:3000).

## Ghi chú
Phần state/logic/event **chưa được sinh tự động** — Builder chỉ xuất cấu trúc UI. Bạn tự viết tiếp phần này, hoặc dùng AI coding agent (Cursor, Claude Code...) dựa trên khung UI đã có sẵn trong \`app/\` và \`components/\`.
`;

export function getProjectTemplateFiles(projectName: string): GeneratedFile[] {
  const slug = slugifyPathSegment(projectName);

  return [
    { path: "package.json", content: PACKAGE_JSON(slug) },
    { path: "tsconfig.json", content: TSCONFIG_JSON },
    { path: "next.config.ts", content: NEXT_CONFIG_TS },
    { path: "postcss.config.mjs", content: POSTCSS_CONFIG_MJS },
    { path: "app/globals.css", content: GLOBALS_CSS },
    { path: "app/layout.tsx", content: LAYOUT_TSX(projectName) },
    { path: "lib/utils.ts", content: LIB_UTILS_TS },
    { path: ".gitignore", content: GITIGNORE },
    { path: "README.md", content: README_MD(projectName) },
  ];
}
