name: Supabase Migration

on:
  push:
    branches: [ master ]
    paths:
      - 'supabase/migrations/**'  # Chỉ kích hoạt khi có thay đổi ở đây

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase link --project-ref fpnlxkexqvaoaxrktori
          supabase db push
